#!/bin/bash

# Удаленный деплой для GitHub Actions (Docker версия)
# Использование:
#   ./deploy/remote.sh <host> <user> [--key-file <path>]
# Переменные окружения:
#   SSH_KEY - содержимое приватного ключа (для GitHub Actions)
#   SSH_HOST - хост для подключения
#   SSH_USER - пользователь для подключения
#   SECRET_KEY - Flask secret key
#   MINIO_ROOT_USER - MinIO username
#   MINIO_ROOT_PASSWORD - MinIO password

set -e

HOST="${SSH_HOST:-$1}"
USER="${SSH_USER:-${2:-root}}"
KEY_FILE=""

# Парсинг аргументов
shift 2 2>/dev/null || true
while [[ $# -gt 0 ]]; do
    case $1 in
        --key-file)
            KEY_FILE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 <host> <user> [--key-file <path>]"
            echo ""
            echo "Arguments:"
            echo "  host              SSH host (or use SSH_HOST env)"
            echo "  user              SSH user (or use SSH_USER env)"
            echo ""
            echo "Options:"
            echo "  --key-file PATH   Path to SSH private key"
            echo ""
            echo "Environment variables:"
            echo "  SSH_KEY              SSH private key content (for CI/CD)"
            echo "  SSH_HOST             SSH host"
            echo "  SSH_USER             SSH user"
            echo "  SECRET_KEY           Flask secret key"
            echo "  MINIO_ROOT_USER      MinIO username"
            echo "  MINIO_ROOT_PASSWORD  MinIO password"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -z "$HOST" ]; then
    echo "Error: HOST is required"
    echo "Use: $0 <host> <user> or set SSH_HOST environment variable"
    exit 1
fi

# Проверка обязательных переменных для CI/CD
if [ -n "$SSH_KEY" ]; then
    # Режим CI/CD - проверяем наличие secrets
    if [ -z "$SECRET_KEY" ]; then
        echo "Error: SECRET_KEY is required"
        echo "Add SECRET_KEY to GitHub Secrets"
        exit 1
    fi
    if [ -z "$MINIO_ROOT_USER" ] || [ -z "$MINIO_ROOT_PASSWORD" ]; then
        echo "Error: MINIO_ROOT_USER and MINIO_ROOT_PASSWORD are required"
        echo "Add them to GitHub Secrets"
        exit 1
    fi
fi

echo "🚀 Remote deployment to $HOST (Docker)"
echo "======================================="

# Настройка SSH ключа из переменной окружения (для GitHub Actions)
if [ -n "$SSH_KEY" ]; then
    echo "Setting up SSH key from environment..."
    mkdir -p ~/.ssh
    echo "$SSH_KEY" > ~/.ssh/deploy_key
    chmod 600 ~/.ssh/deploy_key
    KEY_FILE=~/.ssh/deploy_key
fi

# Формируем SSH команду
SSH_CMD="ssh -o StrictHostKeyChecking=no"
SCP_CMD="scp -o StrictHostKeyChecking=no"
if [ -n "$KEY_FILE" ]; then
    SSH_CMD="$SSH_CMD -i $KEY_FILE"
    SCP_CMD="$SCP_CMD -i $KEY_FILE"
fi

echo "Connecting to $USER@$HOST..."
echo ""

# Создаем .env локально и копируем на сервер (только в режиме CI/CD)
if [ -n "$SECRET_KEY" ]; then
    echo "📝 Creating .env file..."

    ENV_CONTENT="# DOCX Template Filler - Environment Configuration
# Auto-generated by GitHub Actions on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# DO NOT EDIT MANUALLY - managed by CI/CD

SECRET_KEY=${SECRET_KEY}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
S3_ENDPOINT=minio:9000
S3_BUCKET=templates
FLASK_ENV=production
"

    # Создаем временный файл
    ENV_TMP=$(mktemp)
    echo "$ENV_CONTENT" > "$ENV_TMP"

    # Копируем на сервер
    echo "📤 Uploading .env to server..."
    $SCP_CMD "$ENV_TMP" "$USER@$HOST:/tmp/.env.new"
    rm -f "$ENV_TMP"
fi

# Выполняем обновление на удаленном сервере
$SSH_CMD $USER@$HOST << 'ENDSSH'
set -e

APP_DIR="/home/docxapp/docx-template-filler"

echo "📥 Updating on server (Docker deployment)..."
cd $APP_DIR || exit 1

# Обновление кода
echo "1️⃣ Pulling latest code..."
su - docxapp -c "cd docx-template-filler && git fetch origin && git reset --hard origin/main"

# Перемещаем .env если был загружен
echo "2️⃣ Setting up environment..."
if [ -f "/tmp/.env.new" ]; then
    mv /tmp/.env.new "$APP_DIR/.env"
    chown docxapp:docxapp "$APP_DIR/.env"
    chmod 600 "$APP_DIR/.env"
    echo "   .env updated from CI/CD"
elif [ ! -f "$APP_DIR/.env" ]; then
    echo "❌ Error: .env file not found!"
    echo "Add SECRET_KEY, MINIO_ROOT_USER, MINIO_ROOT_PASSWORD to GitHub Secrets"
    exit 1
fi

# Создание директорий для volumes
echo "3️⃣ Creating data directories..."
su - docxapp -c "cd docx-template-filler && mkdir -p data uploads output docx_templates"

# Остановка старого systemd сервиса (если запущен)
echo "4️⃣ Stopping old systemd service (if running)..."
systemctl stop docxapp 2>/dev/null || true
systemctl disable docxapp 2>/dev/null || true

# Сборка и запуск Docker
echo "5️⃣ Building and starting Docker containers..."
su - docxapp -c "cd docx-template-filler && docker compose down 2>/dev/null || true"
su - docxapp -c "cd docx-template-filler && docker compose build --no-cache"
su - docxapp -c "cd docx-template-filler && docker compose up -d"

sleep 5

# Проверка
echo ""
echo "6️⃣ Checking status..."
su - docxapp -c "cd docx-template-filler && docker compose ps"

echo ""
echo "Waiting for application to start..."
sleep 5

RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:5000/health" || echo "000")
if [ "$RESPONSE" = "200" ]; then
    echo ""
    echo "✅ Application is running (HTTP $RESPONSE)"
else
    echo ""
    echo "⚠️  Application status: HTTP $RESPONSE"
    echo "Checking logs..."
    su - docxapp -c "cd docx-template-filler && docker compose logs --tail=20 web"
    exit 1
fi

ENDSSH

echo ""
echo "======================================="
echo "✅ Docker deployment complete!"
echo "======================================="

# Очистка временного ключа
if [ -f ~/.ssh/deploy_key ]; then
    rm -f ~/.ssh/deploy_key
fi

exit 0
